### ISSUE TITLE
Stability?

### ISSUE THREAD

**Issue by geovens** [Morteza-Rastgoo/Sony-Android-TV-VPN-Crash-Fixer#1]
Hi Morteza-Rastgoo,

This thing looks promising. I could use apps like Tasker to do the same thing (i.e. auto close VPN before screen off), but I fear that apps like Tasker may be too bloated for a small and simple task. So I prefer this small app that just fixes the thing.

However as this is pretty new and I may be the first user, may I ask about the stability of this app? Is it expected to work on Android 7.0? Do you think it's stable enough to be used by uninformed users like me? If something fails in this app, is there possibility that some damage or trouble could be caused to the system? Should I be hesitating to try it on my Sony TV? If I try it and it doesn't work, that's fine, but you may understand that I can't take risks of system damage.

Thanks for the app.

**Comment by Morteza-Rastgoo** [comment]
Hello @geovens 
As you mentioned, using a simple app to to the job is the aim I followed.
For sake of stability, you can help me find out how this app works on your side as I don't have other devices to test the app but I think It should work as the application job is so simple:
1- Wait for screen to turn off
2- Try to connect a dummy vpn service to let the os disconnect any previously connected vpn.

Also,
## Press Star ⭐ to If this app helps you!
